[2020-11-05 09:37:54,475] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 09:37:54,548] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 3058
[2020-11-05 09:37:54,666] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-11-05 09:37:54,667] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2191
[2020-11-05 09:38:03,720] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 09:38:03,736] [views.py:26] [views:index] [INFO]- 缓存中的key为：8662620a1f0711ebb4bf5800e3fb0696----浏览器中的key为:8662620a1f0711ebb4bf5800e3fb0696
[2020-11-05 09:38:07,206] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21386
[2020-11-05 09:38:07,230] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,231] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,248] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,253] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,259] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,264] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,265] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,269] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_Nbhv7zS.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,277] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l_Cb48EuQ.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,280] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_8LDT5UV.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,282] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_wIyACGh.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,286] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s_VzPsWar.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,287] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/111s.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,288] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_uTwIBrp.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,297] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,298] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:07,300] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s_aLIY1WH.jpg HTTP/1.1" 304 0
[2020-11-05 09:38:11,381] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 09:38:11,389] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 09:38:11,427] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2715
[2020-11-05 09:38:30,043] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 09:38:30,058] [views.py:26] [views:index] [INFO]- 缓存中的key为：907729401f0711ebaee65800e3fb0696----浏览器中的key为:907729401f0711ebaee65800e3fb0696
[2020-11-05 09:38:30,144] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21859
[2020-11-05 09:38:32,248] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 10:18:35,535] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:907729401f0711ebaee65800e3fb0696
[2020-11-05 10:18:35,551] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 10:18:35,571] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 10:18:35,614] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2626
[2020-11-05 10:18:50,721] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 10:18:50,753] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2672
[2020-11-05 10:19:05,702] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 10:19:05,716] [views.py:26] [views:index] [INFO]- 缓存中的key为：3563f48a1f0d11eba9e65800e3fb0696----浏览器中的key为:3563f48a1f0d11eba9e65800e3fb0696
[2020-11-05 10:19:05,879] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21859
[2020-11-05 10:19:08,618] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 10:19:53,184] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /novels/author_edit HTTP/1.1" 302 0
[2020-11-05 10:19:53,212] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6019
[2020-11-05 10:23:37,187] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6500
[2020-11-05 10:24:28,973] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 10:37:01,594] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 10:37:03,240] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:3563f48a1f0d11eba9e65800e3fb0696
[2020-11-05 10:37:03,248] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 10:37:03,257] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 10:37:03,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2997
[2020-11-05 10:37:15,141] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 10:37:15,170] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2446
[2020-11-05 10:37:38,151] [base.py:93] [base:get_response] [WARNING]- Not Found: /
[2020-11-05 10:37:38,153] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2140
[2020-11-05 10:45:55,070] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 10:45:55,107] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2954
[2020-11-05 10:46:10,996] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 10:46:11,011] [views.py:26] [views:index] [INFO]- 缓存中的key为：069b8e8a1f1111eb987b5800e3fb0696----浏览器中的key为:069b8e8a1f1111eb987b5800e3fb0696
[2020-11-05 10:46:11,036] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 45, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 10:46:11,420] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 233335
[2020-11-05 11:24:58,091] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:069b8e8a1f1111eb987b5800e3fb0696
[2020-11-05 11:24:58,099] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 11:24:58,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 11:24:58,158] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2606
[2020-11-05 11:25:11,216] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 11:25:11,251] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2227
[2020-11-05 11:25:23,422] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 11:25:23,436] [views.py:26] [views:index] [INFO]- 缓存中的key为：7b2b87b81f1611ebbe4b5800e3fb0696----浏览器中的key为:7b2b87b81f1611ebbe4b5800e3fb0696
[2020-11-05 11:25:23,457] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 45, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 11:25:23,612] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 233335
[2020-11-05 12:44:33,676] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:7b2b87b81f1611ebbe4b5800e3fb0696
[2020-11-05 12:44:33,691] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 12:44:33,707] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 12:44:33,751] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2848
[2020-11-05 12:44:52,382] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 12:44:52,403] [views.py:26] [views:index] [INFO]- 缓存中的key为：99a555361f2111ebbbeb5800e3fb0696----浏览器中的key为:99a555361f2111ebbbeb5800e3fb0696
[2020-11-05 12:44:52,426] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 45, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 12:44:52,692] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 232829
[2020-11-05 12:45:47,317] [views.py:26] [views:index] [INFO]- 缓存中的key为：99a555361f2111ebbbeb5800e3fb0696----浏览器中的key为:99a555361f2111ebbbeb5800e3fb0696
[2020-11-05 12:45:47,351] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 45, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 12:45:47,606] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 232816
[2020-11-05 12:49:52,348] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 12:49:52,400] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2315
[2020-11-05 12:50:00,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 12:50:00,541] [views.py:26] [views:index] [INFO]- 缓存中的key为：579229341f2211eba8cc5800e3fb0696----浏览器中的key为:579229341f2211eba8cc5800e3fb0696
[2020-11-05 12:50:00,562] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 46, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 12:50:00,810] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 232924
[2020-11-05 14:23:48,542] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:23:48,609] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2589
[2020-11-05 14:23:52,599] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:23:52,645] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2463
[2020-11-05 14:24:05,328] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 14:24:05,365] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2466
[2020-11-05 14:24:14,970] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.20100795817303974 HTTP/1.1" 200 2374
[2020-11-05 14:24:19,681] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:24:19,695] [views.py:26] [views:index] [INFO]- 缓存中的key为：796c02e81f2f11eb8b445800e3fb0696----浏览器中的key为:796c02e81f2f11eb8b445800e3fb0696
[2020-11-05 14:24:19,718] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 46, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 14:24:19,912] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 232924
[2020-11-05 14:30:41,822] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:796c02e81f2f11eb8b445800e3fb0696
[2020-11-05 14:30:41,930] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 14:30:41,999] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:30:42,142] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2696
[2020-11-05 14:30:51,644] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.47304196659445763 HTTP/1.1" 200 2454
[2020-11-05 14:30:53,693] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.42246810767844534 HTTP/1.1" 200 2636
[2020-11-05 14:30:54,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.7168498797053231 HTTP/1.1" 200 2718
[2020-11-05 14:30:56,144] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.03970251304460004 HTTP/1.1" 200 2727
[2020-11-05 14:30:57,595] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.2625955336618786 HTTP/1.1" 200 2920
[2020-11-05 14:31:02,684] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:31:02,740] [views.py:26] [views:index] [INFO]- 缓存中的key为：6d70c55c1f3011ebb7c95800e3fb0696----浏览器中的key为:6d70c55c1f3011ebb7c95800e3fb0696
[2020-11-05 14:33:24,802] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 48, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('5aae962dd1624796a332eb305ce5fb42',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 14:33:25,412] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 235178
[2020-11-05 14:37:02,816] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:6d70c55c1f3011ebb7c95800e3fb0696
[2020-11-05 14:37:02,847] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 14:37:02,914] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:37:03,051] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2920
[2020-11-05 14:37:11,308] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:37:11,359] [views.py:26] [views:index] [INFO]- 缓存中的key为：507c51681f3111eb90dc5800e3fb0696----浏览器中的key为:507c51681f3111eb90dc5800e3fb0696
[2020-11-05 14:37:23,784] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21584
[2020-11-05 14:37:23,943] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 200 138618
[2020-11-05 14:37:23,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 200 161173
[2020-11-05 14:37:23,962] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 200 335654
[2020-11-05 14:37:23,989] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 200 335654
[2020-11-05 14:37:23,999] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 200 335654
[2020-11-05 14:37:24,010] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s.jpg HTTP/1.1" 200 15649
[2020-11-05 14:37:24,046] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 200 356232
[2020-11-05 14:37:24,084] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_Nbhv7zS.jpg HTTP/1.1" 200 138618
[2020-11-05 14:37:24,121] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_8LDT5UV.jpg HTTP/1.1" 200 138618
[2020-11-05 14:37:24,126] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_wIyACGh.jpg HTTP/1.1" 200 138618
[2020-11-05 14:37:24,171] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l_Cb48EuQ.jpg HTTP/1.1" 200 356232
[2020-11-05 14:37:24,197] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s_VzPsWar.jpg HTTP/1.1" 200 15649
[2020-11-05 14:37:24,253] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/111s.jpg HTTP/1.1" 200 13525
[2020-11-05 14:37:24,256] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l_uTwIBrp.jpg HTTP/1.1" 200 138618
[2020-11-05 14:37:24,264] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/8797s_aLIY1WH.jpg HTTP/1.1" 200 15649
[2020-11-05 14:37:24,266] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 200 15649
[2020-11-05 14:37:24,278] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 200 138618
[2020-11-05 14:39:36,439] [views.py:26] [views:index] [INFO]- 缓存中的key为：507c51681f3111eb90dc5800e3fb0696----浏览器中的key为:507c51681f3111eb90dc5800e3fb0696
[2020-11-05 14:39:43,999] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 48, in index
    return render(request, 'novel/index.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('aaabbbccc',)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-11-05 14:39:44,538] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 234975
[2020-11-05 14:46:15,551] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:507c51681f3111eb90dc5800e3fb0696
[2020-11-05 14:46:15,572] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 14:46:15,593] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:46:15,658] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2514
[2020-11-05 14:46:25,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:46:25,473] [views.py:26] [views:index] [INFO]- 缓存中的key为：99e8ad6e1f3211eba04b5800e3fb0696----浏览器中的key为:99e8ad6e1f3211eba04b5800e3fb0696
[2020-11-05 14:46:25,662] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21570
[2020-11-05 14:49:34,161] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 14:49:34,180] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:49:34,226] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2760
[2020-11-05 14:49:46,715] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:49:46,730] [views.py:26] [views:index] [INFO]- 缓存中的key为：1046ec341f3311eba3745800e3fb0696----浏览器中的key为:1046ec341f3311eba3745800e3fb0696
[2020-11-05 14:49:46,954] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 14:49:49,130] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 14:49:54,169] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 14:49:54,261] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 14:50:39,679] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 14:50:42,780] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 14:50:42,793] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:50:42,829] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2614
[2020-11-05 14:50:53,846] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:50:53,861] [views.py:26] [views:index] [INFO]- 缓存中的key为：392c438c1f3311ebb0bf5800e3fb0696----浏览器中的key为:392c438c1f3311ebb0bf5800e3fb0696
[2020-11-05 14:50:54,068] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 14:50:55,609] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 14:53:59,882] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:54:03,779] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 10096
[2020-11-05 14:54:03,798] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57304l_7bp9ebG.jpg HTTP/1.1" 200 138618
[2020-11-05 14:54:03,802] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/58950l_ENR4gcI.jpg HTTP/1.1" 200 335654
[2020-11-05 14:54:05,865] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 8764
[2020-11-05 14:54:05,884] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/58950l.jpg HTTP/1.1" 200 335654
[2020-11-05 14:54:06,842] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/3 HTTP/1.1" 200 9675
[2020-11-05 14:54:06,867] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/8797s.jpg HTTP/1.1" 200 15649
[2020-11-05 14:54:06,870] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/111s.jpg HTTP/1.1" 200 13525
[2020-11-05 14:54:07,777] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/4 HTTP/1.1" 200 8787
[2020-11-05 14:54:07,792] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/111s_YM8x2d4.jpg HTTP/1.1" 200 13525
[2020-11-05 14:54:08,967] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 8819
[2020-11-05 14:54:08,984] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57304l_0H2be4N.jpg HTTP/1.1" 200 138618
[2020-11-05 14:54:10,006] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/6 HTTP/1.1" 200 8821
[2020-11-05 14:54:10,023] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57840l_RiIsmEx.jpg HTTP/1.1" 200 161173
[2020-11-05 14:54:12,833] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/6 HTTP/1.1" 200 8821
[2020-11-05 14:54:23,932] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9519
[2020-11-05 14:54:25,583] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 14:54:27,552] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:55:34,912] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:56:03,426] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:56:06,763] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:56:09,035] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:56:20,794] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 14:56:37,260] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 14:56:39,713] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 14:56:40,255] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 14:56:42,407] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:392c438c1f3311ebb0bf5800e3fb0696
[2020-11-05 14:56:42,415] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 14:56:42,425] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:56:42,457] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2780
[2020-11-05 14:56:44,535] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:56:44,573] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2593
[2020-11-05 14:56:45,223] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:56:45,269] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2722
[2020-11-05 14:57:25,441] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:57:25,544] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2763
[2020-11-05 14:57:43,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:57:43,608] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2630
[2020-11-05 14:57:44,560] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:57:44,646] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2508
[2020-11-05 14:58:05,353] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 14:58:05,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2533
[2020-11-05 14:58:05,614] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-11-05 14:58:05,615] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2191
[2020-11-05 14:58:16,354] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 14:58:16,366] [views.py:26] [views:index] [INFO]- 缓存中的key为：40f5740a1f3411eb868d5800e3fb0696----浏览器中的key为:40f5740a1f3411eb868d5800e3fb0696
[2020-11-05 14:58:16,546] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 14:58:18,882] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 156, in show_bookrack
    print(user)
OSError: [Errno 22] Invalid argument
[2020-11-05 14:58:18,922] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 75612
[2020-11-05 15:03:08,732] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 156, in show_bookrack
    print(user)
OSError: [Errno 22] Invalid argument
[2020-11-05 15:03:08,773] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 75747
[2020-11-05 15:03:38,475] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:03:50,440] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:03:51,955] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:40f5740a1f3411eb868d5800e3fb0696
[2020-11-05 15:03:51,963] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 15:03:51,973] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 15:03:52,009] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2951
[2020-11-05 15:04:02,162] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 15:04:02,176] [views.py:26] [views:index] [INFO]- 缓存中的key为：0f8fb54a1f3511eb84b55800e3fb0696----浏览器中的key为:0f8fb54a1f3511eb84b55800e3fb0696
[2020-11-05 15:04:02,341] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:04:03,798] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 8819
[2020-11-05 15:04:05,400] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 10096
[2020-11-05 15:04:06,828] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:04:07,718] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 15:04:09,276] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:04:11,355] [views.py:26] [views:index] [INFO]- 缓存中的key为：0f8fb54a1f3511eb84b55800e3fb0696----浏览器中的key为:0f8fb54a1f3511eb84b55800e3fb0696
[2020-11-05 15:04:11,443] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:04:13,105] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:04:17,127] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:04:20,636] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:04:22,591] [views.py:26] [views:index] [INFO]- 缓存中的key为：0f8fb54a1f3511eb84b55800e3fb0696----浏览器中的key为:0f8fb54a1f3511eb84b55800e3fb0696
[2020-11-05 15:04:22,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:04:56,073] [views.py:26] [views:index] [INFO]- 缓存中的key为：0f8fb54a1f3511eb84b55800e3fb0696----浏览器中的key为:0f8fb54a1f3511eb84b55800e3fb0696
[2020-11-05 15:04:56,188] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:04:57,619] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 15:04:59,708] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:05:03,755] [views.py:26] [views:index] [INFO]- 缓存中的key为：0f8fb54a1f3511eb84b55800e3fb0696----浏览器中的key为:0f8fb54a1f3511eb84b55800e3fb0696
[2020-11-05 15:05:03,836] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:05:04,520] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:05:08,681] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 15:05:08,692] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 15:05:08,723] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2580
[2020-11-05 15:05:16,469] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 15:05:16,505] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2241
[2020-11-05 15:05:24,816] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 15:05:24,832] [views.py:26] [views:index] [INFO]- 缓存中的key为：3d4a207e1f3511eb98ac5800e3fb0696----浏览器中的key为:3d4a207e1f3511eb98ac5800e3fb0696
[2020-11-05 15:05:24,916] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21573
[2020-11-05 15:05:27,160] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 9518
[2020-11-05 15:05:31,862] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 9623
[2020-11-05 15:05:32,837] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 8291
[2020-11-05 15:05:33,936] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/3 HTTP/1.1" 200 9202
[2020-11-05 15:05:34,597] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/4 HTTP/1.1" 200 8314
[2020-11-05 15:05:35,359] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 8346
[2020-11-05 15:05:35,948] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/6 HTTP/1.1" 200 8348
[2020-11-05 15:05:36,603] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9046
[2020-11-05 15:05:37,450] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9252
[2020-11-05 15:05:39,384] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 挂机死神就能变强>, <Novels: 我的神通有技术>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 挂机死神就能变强>, 'user': <User: admin222>, 'username': 'admin222', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': 'aaabbbccc', 'request': <WSGIRequest: GET '/novels/detail/aaabbbccc'>}
[2020-11-05 15:05:39,410] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/aaabbbccc HTTP/1.1" 200 8996
[2020-11-05 15:05:39,426] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57840l_iuMjulY.jpg HTTP/1.1" 200 161173
[2020-11-05 15:05:49,644] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 9518
[2020-11-05 15:05:52,510] [views.py:26] [views:index] [INFO]- 缓存中的key为：3d4a207e1f3511eb98ac5800e3fb0696----浏览器中的key为:3d4a207e1f3511eb98ac5800e3fb0696
[2020-11-05 15:05:52,596] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21573
[2020-11-05 15:05:55,018] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 8291
[2020-11-05 15:05:56,803] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': <Chapter: 第一章  快捷快递放假就>, 'new_novels': <QuerySet [<Novels: 奋斗在蛮荒时代>]>, 'hits_novel': '已点赞', 'novel': <Novels: 奋斗在蛮荒时代>, 'user': <User: admin222>, 'username': 'admin222', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '1111', 'request': <WSGIRequest: GET '/novels/detail/1111'>}
[2020-11-05 15:05:56,815] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/1111 HTTP/1.1" 200 9310
[2020-11-05 15:05:59,800] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/44444444 HTTP/1.1" 200 14001
[2020-11-05 15:06:01,061] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=44444444 HTTP/1.1" 200 17
[2020-11-05 15:06:03,888] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 9518
[2020-11-05 15:06:07,646] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9252
[2020-11-05 15:06:22,822] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 15:06:22,836] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 15:06:22,945] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2370
[2020-11-05 15:06:31,958] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 15:06:31,973] [views.py:26] [views:index] [INFO]- 缓存中的key为：697b7a981f3511eb94ce5800e3fb0696----浏览器中的key为:697b7a981f3511eb94ce5800e3fb0696
[2020-11-05 15:06:32,060] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:06:34,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 10096
[2020-11-05 15:06:35,961] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/3 HTTP/1.1" 200 9675
[2020-11-05 15:06:36,480] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/4 HTTP/1.1" 200 8787
[2020-11-05 15:06:37,231] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9519
[2020-11-05 15:06:38,203] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9519
[2020-11-05 15:06:39,090] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:06:40,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 15:06:48,491] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:06:50,382] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:07:35,146] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7001
[2020-11-05 15:08:52,679] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:08:59,100] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 15:09:15,059] [views.py:26] [views:index] [INFO]- 缓存中的key为：697b7a981f3511eb94ce5800e3fb0696----浏览器中的key为:697b7a981f3511eb94ce5800e3fb0696
[2020-11-05 15:09:15,293] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:09:17,318] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:09:18,146] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 15:09:19,287] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7001
[2020-11-05 15:09:30,722] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:09:34,727] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 15:09:38,417] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:10:14,061] [views.py:26] [views:index] [INFO]- 缓存中的key为：697b7a981f3511eb94ce5800e3fb0696----浏览器中的key为:697b7a981f3511eb94ce5800e3fb0696
[2020-11-05 15:10:14,159] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:10:15,041] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7001
[2020-11-05 15:11:07,676] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7001
[2020-11-05 15:11:09,823] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7001
[2020-11-05 15:11:55,127] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:11:56,844] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:11:57,694] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:11:58,386] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:12:03,543] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:12:04,370] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:12:04,900] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:12:05,149] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7003
[2020-11-05 15:14:05,902] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:14:09,069] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:08,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:09,411] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:10,023] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:10,297] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:10,539] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:15:11,469] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 15:24:08,243] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:24:17,534] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:697b7a981f3511eb94ce5800e3fb0696
[2020-11-05 15:24:17,542] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 15:24:17,551] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 15:24:17,585] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2786
[2020-11-05 15:24:36,567] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4332
[2020-11-05 15:24:36,603] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2474
[2020-11-05 15:24:45,611] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.4746854882154663 HTTP/1.1" 200 2727
[2020-11-05 15:24:46,827] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.8600024554089598 HTTP/1.1" 200 2857
[2020-11-05 15:24:52,239] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 15:24:52,275] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2485
[2020-11-05 15:25:02,477] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 15:25:02,514] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2348
[2020-11-05 15:25:09,632] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.3414114039841334 HTTP/1.1" 200 2756
[2020-11-05 15:25:10,623] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.7009480498802838 HTTP/1.1" 200 2712
[2020-11-05 15:25:16,477] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 15:25:16,491] [views.py:26] [views:index] [INFO]- 缓存中的key为：ea100db61f3711eba5705800e3fb0696----浏览器中的key为:ea100db61f3711eba5705800e3fb0696
[2020-11-05 15:25:16,662] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:25:22,673] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 15:25:24,382] [views.py:26] [views:index] [INFO]- 缓存中的key为：ea100db61f3711eba5705800e3fb0696----浏览器中的key为:ea100db61f3711eba5705800e3fb0696
[2020-11-05 15:25:24,466] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 15:25:26,593] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 海贼之文虎大将>, <Novels: 万族之劫>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 海贼之文虎大将>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '11111111', 'request': <WSGIRequest: GET '/novels/detail/11111111'>}
[2020-11-05 15:25:26,605] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 9412
[2020-11-05 15:25:27,942] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-11-05 15:25:30,045] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 15:27:43,324] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 15:27:43,467] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 15:27:46,123] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 15:27:48,562] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 15:27:48,588] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 15:29:12,117] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 15:29:12,141] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 15:30:13,244] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 15:30:13,272] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 16:00:35,949] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 16:01:08,938] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:01:09,063] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 16:01:53,877] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:01:54,004] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7799
[2020-11-05 16:02:46,731] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:02:48,873] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:02:48,899] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:03:17,280] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:03:20,768] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:03:20,794] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:04:32,677] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:04:35,071] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:04:35,093] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:05:04,937] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:05:06,576] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:ea100db61f3711eba5705800e3fb0696
[2020-11-05 16:05:06,584] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 16:05:06,594] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:05:06,626] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2900
[2020-11-05 16:05:16,878] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 16:05:16,934] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2512
[2020-11-05 16:05:27,710] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:05:27,726] [views.py:26] [views:index] [INFO]- 缓存中的key为：9dce621c1f3d11ebbad85800e3fb0696----浏览器中的key为:9dce621c1f3d11ebbad85800e3fb0696
[2020-11-05 16:05:27,906] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:05:30,240] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:06:40,676] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:06:41,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:06:42,364] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:06:43,270] [views.py:26] [views:index] [INFO]- 缓存中的key为：9dce621c1f3d11ebbad85800e3fb0696----浏览器中的key为:9dce621c1f3d11ebbad85800e3fb0696
[2020-11-05 16:06:43,429] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:06:44,322] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:06:46,588] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 16:06:46,599] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:06:46,628] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2441
[2020-11-05 16:06:55,118] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:06:55,133] [views.py:26] [views:index] [INFO]- 缓存中的key为：d969c9a61f3d11ebb32f5800e3fb0696----浏览器中的key为:d969c9a61f3d11ebb32f5800e3fb0696
[2020-11-05 16:06:55,216] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 21573
[2020-11-05 16:06:56,769] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8797
[2020-11-05 16:07:31,918] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 16:07:31,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:07:31,976] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2391
[2020-11-05 16:07:40,230] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:07:40,245] [views.py:26] [views:index] [INFO]- 缓存中的key为：f46e7d921f3d11ebb7265800e3fb0696----浏览器中的key为:f46e7d921f3d11ebb7265800e3fb0696
[2020-11-05 16:07:40,326] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:07:48,441] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:08:13,469] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:13,726] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:14,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:15,416] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:16,005] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:16,221] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:16,789] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:17,491] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:18,007] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:18,269] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:18,723] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:18,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:19,171] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:19,369] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:08:38,922] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6601
[2020-11-05 16:08:39,921] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6601
[2020-11-05 16:08:40,515] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6601
[2020-11-05 16:08:40,767] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6601
[2020-11-05 16:08:41,289] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6601
[2020-11-05 16:08:48,995] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7082
[2020-11-05 16:12:24,221] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:12:36,524] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:13:07,242] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:13:09,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:13:13,765] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:13:55,255] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:14:33,628] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:14:45,072] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:f46e7d921f3d11ebb7265800e3fb0696
[2020-11-05 16:14:45,089] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 16:14:45,106] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:14:45,139] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2680
[2020-11-05 16:14:55,990] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:14:56,003] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:14:56,163] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:14:57,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:15:11,266] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:15:11,468] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:15:12,744] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:15:12,830] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:15:13,578] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:15:13,666] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:15:14,810] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:15:14,898] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:15:15,833] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:15:17,752] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 10096
[2020-11-05 16:15:19,618] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:18:25,536] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:18:25,724] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:18:26,792] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:18:29,892] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:18:53,826] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:18:53,984] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:19:08,777] [views.py:26] [views:index] [INFO]- 缓存中的key为：f6a047861f3e11ebb6c75800e3fb0696----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:19:08,950] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:19:11,350] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 海贼之文虎大将>, <Novels: 万族之劫>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 海贼之文虎大将>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '11111111', 'request': <WSGIRequest: GET '/novels/detail/11111111'>}
[2020-11-05 16:19:11,362] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 9412
[2020-11-05 16:19:12,491] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-11-05 16:19:12,513] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 500 19936
[2020-11-05 16:19:15,383] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:19:52,259] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7798
[2020-11-05 16:19:54,654] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:19:54,680] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:20:18,026] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 海贼之文虎大将>, <Novels: 万族之劫>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 海贼之文虎大将>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '11111111', 'request': <WSGIRequest: GET '/novels/detail/11111111'>}
[2020-11-05 16:20:18,164] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 9412
[2020-11-05 16:20:19,029] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 海贼之文虎大将>, <Novels: 万族之劫>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 海贼之文虎大将>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '11111111', 'request': <WSGIRequest: GET '/novels/detail/11111111'>}
[2020-11-05 16:20:19,039] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 9412
[2020-11-05 16:20:21,216] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6634
[2020-11-05 16:22:18,312] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6584
[2020-11-05 16:22:36,654] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6674
[2020-11-05 16:22:38,364] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6674
[2020-11-05 16:22:39,401] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6674
[2020-11-05 16:22:41,184] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6674
[2020-11-05 16:22:47,204] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-11-05 16:22:47,217] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 500 19936
[2020-11-05 16:22:48,626] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7781
[2020-11-05 16:23:16,852] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7781
[2020-11-05 16:23:18,047] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7781
[2020-11-05 16:23:20,416] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:23:20,439] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:23:22,261] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:23:22,775] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:23:22,991] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:23:23,185] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:23:26,505] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:f6a047861f3e11ebb6c75800e3fb0696
[2020-11-05 16:23:26,513] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 16:23:26,522] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:23:26,554] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2881
[2020-11-05 16:23:36,456] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-11-05 16:23:36,489] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2599
[2020-11-05 16:23:47,117] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:23:47,133] [views.py:26] [views:index] [INFO]- 缓存中的key为：2d6a0bd21f4011eb92765800e3fb0696----浏览器中的key为:2d6a0bd21f4011eb92765800e3fb0696
[2020-11-05 16:23:47,222] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:23:49,027] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:24:47,437] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7065
[2020-11-05 16:24:59,847] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:02,284] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:04,098] [views.py:26] [views:index] [INFO]- 缓存中的key为：2d6a0bd21f4011eb92765800e3fb0696----浏览器中的key为:2d6a0bd21f4011eb92765800e3fb0696
[2020-11-05 16:25:04,270] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:25:05,714] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:27,164] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 168, in show_bookrack
    return render(request,'novel/show_bookrack.html',locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Envs\Django2020\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Envs\Django2020\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 955, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 888, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Envs\Django2020\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 891, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from '|'
[2020-11-05 16:25:27,329] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 199441
[2020-11-05 16:25:38,094] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:39,028] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:39,457] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:39,659] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:39,897] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:40,103] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:40,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:40,507] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:40,675] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:44,370] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:25:45,784] [views.py:26] [views:index] [INFO]- 缓存中的key为：2d6a0bd21f4011eb92765800e3fb0696----浏览器中的key为:2d6a0bd21f4011eb92765800e3fb0696
[2020-11-05 16:25:45,869] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:25:48,019] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 海贼之文虎大将>, <Novels: 万族之劫>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 海贼之文虎大将>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '11111111', 'request': <WSGIRequest: GET '/novels/detail/11111111'>}
[2020-11-05 16:25:48,031] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 9412
[2020-11-05 16:25:49,412] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-11-05 16:25:49,425] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 500 19936
[2020-11-05 16:25:51,145] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7781
[2020-11-05 16:25:55,594] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/delete_collect/11111111 HTTP/1.1" 302 0
[2020-11-05 16:25:55,617] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:26:01,419] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7155
[2020-11-05 16:26:02,506] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 10096
[2020-11-05 16:26:03,096] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 8764
[2020-11-05 16:26:03,830] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/4 HTTP/1.1" 200 8787
[2020-11-05 16:26:04,312] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 8819
[2020-11-05 16:26:04,764] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/6 HTTP/1.1" 200 8821
[2020-11-05 16:26:05,208] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9519
[2020-11-05 16:26:05,915] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 16:26:06,807] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 16:26:07,715] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 16:26:14,160] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 16:26:15,729] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7046
[2020-11-05 16:26:45,827] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:28:36,299] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:28:36,994] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:28:37,513] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:28:37,977] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:28:40,358] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 16:30:17,612] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 282, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:30:17,781] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187283
[2020-11-05 16:31:55,572] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 282, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:31:55,647] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187148
[2020-11-05 16:32:28,965] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 282, in show_author_novels
    return render(request, 'novel/show_author_novels.html',locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:32:29,117] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187281
[2020-11-05 16:32:32,187] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 282, in show_author_novels
    return render(request, 'novel/show_author_novels.html',locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:32:32,261] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187146
[2020-11-05 16:34:46,314] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:34:46,397] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187236
[2020-11-05 16:34:53,381] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 16:34:54,489] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/ranking_list HTTP/1.1" 200 9519
[2020-11-05 16:34:55,504] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/all_novels HTTP/1.1" 200 9725
[2020-11-05 16:34:56,745] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_edit HTTP/1.1" 200 10062
[2020-11-05 16:34:57,574] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:34:57,646] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187101
[2020-11-05 16:35:34,798] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-11-05 16:35:34,814] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 16:35:34,845] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2700
[2020-11-05 16:35:44,586] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 16:35:44,599] [views.py:26] [views:index] [INFO]- 缓存中的key为：df8265be1f4111eba7745800e3fb0696----浏览器中的key为:df8265be1f4111eba7745800e3fb0696
[2020-11-05 16:35:44,784] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22046
[2020-11-05 16:35:46,494] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:35:46,572] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187095
[2020-11-05 16:37:05,407] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:37:05,477] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187233
[2020-11-05 16:37:06,584] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:37:06,654] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187233
[2020-11-05 16:37:07,432] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:37:07,503] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187233
[2020-11-05 16:37:08,289] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_collect' with arguments '('',)' not found. 1 pattern(s) tried: ['novels\\/delete_collect\\/(?P<uid>[^/]+)$']
[2020-11-05 16:37:08,358] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 187233
[2020-11-05 16:37:51,428] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7644
[2020-11-05 16:37:52,770] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7644
[2020-11-05 16:38:02,952] [views.py:85] [views:novel_detail] [INFO]- {'new_chapter': None, 'new_novels': <QuerySet [<Novels: 挂机死神就能变强>, <Novels: 我的神通有技术>]>, 'hits_novel': <QuerySet []>, 'novel': <Novels: 挂机死神就能变强>, 'user': <User: lijunhan77>, 'username': 'lijunhan77', 'types': <QuerySet [<NovelsType: 玄幻>, <NovelsType: 修真>, <NovelsType: 都市>, <NovelsType: 穿越>, <NovelsType: 网游>, <NovelsType: 科幻>, <NovelsType: 奇幻>, <NovelsType: 武侠>, <NovelsType: 仙侠>, <NovelsType: 言情>, <NovelsType: 历史>, <NovelsType: 军事>, <NovelsType: 游戏>, <NovelsType: 竞技>, <NovelsType: 异灵>]>, 'gid': '111111111111', 'request': <WSGIRequest: GET '/novels/detail/111111111111'>}
[2020-11-05 16:38:02,964] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/111111111111 HTTP/1.1" 200 9478
[2020-11-05 16:38:02,985] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57840l_iuMjulY.jpg HTTP/1.1" 304 0
[2020-11-05 16:39:29,358] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7644
[2020-11-05 16:39:38,335] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/delete_collect/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 176, in delete_collect
    MyBookrack_novel.is_delete = '1'
AttributeError: 'NoneType' object has no attribute 'is_delete'
[2020-11-05 16:39:38,389] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/delete_collect/111111111111 HTTP/1.1" 500 75941
[2020-11-05 16:40:25,198] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/delete_collect/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 176, in delete_collect
    MyBookrack_novel.is_delete = '1'
AttributeError: 'NoneType' object has no attribute 'is_delete'
[2020-11-05 16:40:25,290] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/delete_collect/111111111111 HTTP/1.1" 500 75941
[2020-11-05 17:39:15,932] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7643
[2020-11-05 17:39:18,360] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/delete_collect/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 176, in delete_collect
    MyBookrack_novel.is_delete = '1'
AttributeError: 'NoneType' object has no attribute 'is_delete'
[2020-11-05 17:39:18,399] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/delete_collect/111111111111 HTTP/1.1" 500 75941
[2020-11-05 17:39:54,411] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/delete_collect/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 177, in delete_collect
    MyBookrack_novel.is_delete = '1'
AttributeError: 'NoneType' object has no attribute 'is_delete'
[2020-11-05 17:39:57,485] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/delete_collect/111111111111 HTTP/1.1" 500 76104
[2020-11-05 17:40:04,591] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/delete_collect/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 177, in delete_collect
    MyBookrack_novel.is_delete = '1'
AttributeError: 'NoneType' object has no attribute 'is_delete'
[2020-11-05 17:40:04,629] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/delete_collect/111111111111 HTTP/1.1" 500 75969
[2020-11-05 17:43:52,853] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_author_novels
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 284, in show_author_novels
    return render(request, 'novel/show_author_novels.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author_delete_novel' with arguments '('111111111111',)' not found. 1 pattern(s) tried: ['novels\\/author_delete_novel$']
[2020-11-05 17:43:53,037] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_author_novels HTTP/1.1" 500 186375
[2020-11-05 17:44:24,121] [views.py:26] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:df8265be1f4111eba7745800e3fb0696
[2020-11-05 17:44:24,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-11-05 17:44:24,168] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-11-05 17:44:24,236] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2391
[2020-11-05 17:44:34,496] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.05155770137101867 HTTP/1.1" 200 2812
[2020-11-05 17:44:40,373] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-11-05 17:44:40,398] [views.py:26] [views:index] [INFO]- 缓存中的key为：7ccbec901f4b11ebab165800e3fb0696----浏览器中的key为:7ccbec901f4b11ebab165800e3fb0696
[2020-11-05 17:44:40,571] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 22049
[2020-11-05 17:44:41,990] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7642
[2020-11-05 17:44:45,450] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/author_delete_novel/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 294, in author_delete_novel
    novel = Novels.objects.filter(novels_id=uid, user_id=user.uid).first()
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\query.py", line 1152, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\query.py", line 1015, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\query.py", line 1378, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'novels_id' into field. Choices are: add_time, author, chapter, collection, desc, hits, image, indexbanner, is_delete, mybookrack, name, status, title, type, type_id, uid, update_time, user, user_id, vicenovels
[2020-11-05 17:44:45,558] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/author_delete_novel/111111111111 HTTP/1.1" 500 117064
[2020-11-05 17:45:22,986] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7642
[2020-11-05 17:45:25,149] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/author_delete_novel/111111111111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 296, in author_delete_novel
    author_delete_novel.save()
AttributeError: 'function' object has no attribute 'save'
[2020-11-05 17:45:25,190] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/author_delete_novel/111111111111 HTTP/1.1" 500 75406
[2020-11-05 17:45:43,563] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7642
[2020-11-05 17:45:45,655] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_delete_novel/111111111111 HTTP/1.1" 302 0
[2020-11-05 17:45:45,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 6550
[2020-11-05 17:46:22,971] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7642
[2020-11-05 17:49:31,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7860
[2020-11-05 17:49:31,944] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57840l_iuMjulY.jpg HTTP/1.1" 304 0
[2020-11-05 17:49:56,900] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7860
[2020-11-05 17:50:00,349] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7858
[2020-11-05 17:50:04,566] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7858
[2020-11-05 17:51:07,949] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7863
[2020-11-05 17:51:09,564] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7863
[2020-11-05 17:51:41,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 17:51:41,944] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 304 0
[2020-11-05 17:52:29,742] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6254
[2020-11-05 17:52:43,517] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6735
[2020-11-05 17:52:46,541] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7863
[2020-11-05 17:52:47,692] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6735
[2020-11-05 17:52:50,467] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7863
[2020-11-05 17:53:10,645] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6239
[2020-11-05 18:01:49,323] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_author_novels HTTP/1.1" 200 7863
[2020-11-05 18:01:51,068] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:01:51,186] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /static/tinymce/themes/advanced/theme.min.js HTTP/1.1" 404 1732
[2020-11-05 18:16:55,405] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:16:55,542] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /static/tinymce/themes/advanced/theme.min.js HTTP/1.1" 404 1732
[2020-11-05 18:16:56,718] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:16:56,789] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /static/tinymce/themes/advanced/theme.min.js HTTP/1.1" 404 1732
[2020-11-05 18:16:57,301] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:16:57,359] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /static/tinymce/themes/advanced/theme.min.js HTTP/1.1" 404 1732
[2020-11-05 18:16:57,862] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:16:57,915] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /static/tinymce/themes/advanced/theme.min.js HTTP/1.1" 404 1732
[2020-11-05 18:20:35,249] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6533
[2020-11-05 18:20:35,282] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:21:39,568] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6529
[2020-11-05 18:21:39,600] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:23,389] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:23,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:25,149] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:25,208] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:25,863] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:25,900] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:26,858] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:26,892] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:30,095] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:30,133] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
[2020-11-05 18:35:30,975] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/author_add_capther HTTP/1.1" 200 6556
[2020-11-05 18:35:31,005] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/tinymce/tinymce.min.js HTTP/1.1" 200 391215
